FROM dockerfile/elasticsearch
RUN /elasticsearch/bin/plugin install OlegKunitsyn/elasticsearch-browser
RUN /elasticsearch/bin/plugin install mobz/elasticsearch-head
RUN /elasticsearch/bin/plugin install jprante/elasticsearch-river-jdbc
